language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
# command to install dependencies
install: 
  - pip install -r requirements.txt
# command to run tests
before_script:
 - mkdir -p media
 - mkdir -p static
 - python manage.py migrate --noinput
 - python manage.py collectstatic --noinput
script:
 - python manage.py test
